version: '3.3'

services:
  landing-service:
    build: ./landing/app/landing
    hostname: landing-service
    ports:
      - 5050:5050
    networks:
      sample:
        aliases:
          - landing-service
          
  addition-service:
    build: ./landing/app/addition
    hostname: addition-service
    ports:
      - 5001:5001
    networks:
      sample:
        aliases:
          - addition-service
        
  subtraction-service:
    build: ./landing/app/subtraction
    hostname: subtraction-service
    ports:
      - 5002:5002
    networks:
      sample:
        aliases:
          - subtraction-service
        
  multiplication-service:
    build: ./landing/app/multiplication
    hostname: multiplication-service
    ports:
      - 5003:5003
    networks:
      sample:
        aliases:
          - multiplication-service
        
  division-service:
    build: ./landing/app/division
    hostname: division-service
    ports:
      - 5004:5004
    networks:
      sample:
        aliases:
          - division-service
        
networks:
  sample:
